### ISSUE TITLE
Support something like a `tag` attribute for the tokens

### ISSUE THREAD

**Issue by lucasmenendez** [vocdoni/census3#44]
Support to a new attribute to the tokens during the creation process which includes some tagging information.

Here is a proposal for the `/token` [`POST`]:

```
{
    "id": "0x1234",
    "type": "erc20|erc721|erc777|erc1155|nation3|wANT",
    "tag": "some,tags,separated,by,commas"
}
```

In the future this `tag` attribute could be used to get filtered results on other API endpoints.

**Comment by marcvelmer** [comment]
`tag` should be optional BTW. If so, I agree with the proposal

**Comment by marcvelmer** [comment]
Added to the SDK
