### ISSUE TITLE
Add the support for Base

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/census3#85]
For the plugin, we need support for Base Network. Try to add this RPC and test the new census in this network.

**Comment by lucasmenendez** [comment]
I've done some tests and any issue found with Goerli Base support.

I've tested the following contracts:
* [ERC20] `0xbdCDBD278467b84F67AEE5737Ddc83A9C054cC29`: 20.017 holders found ([checkout on basescan](https://goerli.basescan.org/token/0xbdCDBD278467b84F67AEE5737Ddc83A9C054cC29))
* [ERC721] `0x35D9185088919680c1d41A0a5fe69Ff7125A12E3`: 16 holders found ([checkout on basescan](https://goerli.basescan.org/token/0x35d9185088919680c1d41a0a5fe69ff7125a12e3))

I also deployed a ERC20 contract for testing (`0xC25A8618c75Dc59003208424241f926dbaEd3A0d`) and I've done an airdrop with some of this tokens to the same addresses that our ERC20 test contract on Ethereum Goerli (`0xf530280176385af31177d78bbfd5ea3f6d07488a`).

Some of our *production* web3 RPC endpoints are provided by Infura and this provider only supports Base Goerli, and does not Base Mainnet. Others providers such as QuickNode or Anker do.

**Comment by jpaulet** [comment]
Ok, let's talk next week then, to plan what to do with "Base Mainnet".

**Comment by lucasmenendez** [comment]
Infura (our current web3 endpoint provider), does not officially support Base Mainnet, but they have experimental support, so will probably they give official support for this chain.

On the other hand, it seems that the Aragon OSx App does not yet support Base Mainnet, so we do not need to include support for this chain at this time.

**Comment by lucasmenendez** [comment]
Official RPC endpoints: https://docs.base.org/using-base/
